[package]
name = "yuri-lexer"
version = "0.0.0-alpha.indev.1"
edition = "2024"
homepage = "https://yuri-lang.dev"
license = "Apache-2.0"

[dependencies]
memchr = { workspace = true }
unicode-xid = { workspace = true }
